- package.json
https://hxshortbreaks.atlassian.net/browse/WEB-5670 
https://hxshortbreaks.atlassian.net/browse/WEB-5674
pull in tagged version of tapestry-prismic and version bump
-
visual and check tests pass
work for the relevant  jiras has been merged in tapestry prismic master branch and tagged 
---
> web5670 version bump and pull in tagged version of tapestry-prismic

- package.json
https://hxshortbreaks.atlassian.net/browse/WEB-5956
version bump to use the encoded tapestry content 
none
eyes
---
> bump tapestry

- package.json
[WEB-6306](https://hxshortbreaks.atlassian.net/browse/WEB-6306)
Different version of [Tapestry](https://github.com/holidayextras/tapestry), without HTML encoding.
N/A
See https://github.com/holidayextras/tapestry/pull/4
---
> Version bumping

- package.json
https://hxshortbreaks.atlassian.net/browse/WEB-4891
Updates the version of tapestry-prismic referenced in package.json.
None
Eyes
---
> Change plugin tapestry to use new version of tapestry prismic

- package.json
https://hxshortbreaks.atlassian.net/browse/WEB-4891
Updates the version of tapestry-prismic (dependency) to include our latest changes in https://github.com/holidayextras/tapestry-prismic/releases/tag/v1.2.0
None
Check the version conforms with the package.json version here: https://github.com/holidayextras/tapestry-prismic/blob/30a9bf8bd188e84452b1e88e755ff6954aaab41b/package.json
---
> Update dependencies and version bump

- package.json
WEB-7667
version bump
none
can be tested on branch FEA-881 of the-works
---
> version bump again

- package.json
WEB-7492
version bumps tapestry-prismic
can you `npm install`? you have probably already tested this
---
> WEB-7492 version bump of tapestry-prismic

- package.json
WEB-7807
version bump to include https://github.com/holidayextras/tapestry-prismic/pull/10
it's only a version bump of tapestry-prismic, only the-works uses this and the-works refers to this by version explicitly so it's safe to merge.
---
> WEB-7807 version bump for structured text (html) 

- package.json
WEB-7807
version bump
none
will not be used anywhere until https://github.com/holidayextras/the-works/pull/193 is merged
---
> version bump, bug fix and up prismic version too WEB-7807

- package.json
https://hxshortbreaks.atlassian.net/browse/WEB-8400
There were problems with the MySQL connection on tapestry-exodus which was causing the works to be non responsive.
This is a version bump for plugin-tapestry.
n/a
---
> Update Tapestry Exodus for mysql connection fix

- LICENSE-MIT
- README.md
- package.json
[WEB-8568](https://hxshortbreaks.atlassian.net/browse/WEB-8568)
Updated the version of tapestry-prismic to 1.5.0
None
---
> WEB-8568 version bump for tapestry-prismic

- package.json
[WEB-9187](https://hxshortbreaks.atlassian.net/browse/WEB-9187)
Updating the version of tapestry prismic from 1.5.0 to 1.6.0
Then the venue products will have faqs.
None
None
---
> WEB-9187 adding new version of tapestry-prismic v1.6.0

- package.json
[WEB-9592](https://hxshortbreaks.atlassian.net/browse/WEB-9592)
Updating tapestry-prismic from `1.6.0` to `1.7.0`
None
---
**Reviewer**
By adding a +1 you are confirming you have...
- Thought about whether this PR needs additional reviewers and requested if necessary.
> WEB-9592 updating tapestry-prismic

- package.json
[WEB-10367](https://hxshortbreaks.atlassian.net/browse/WEB-10367): Package tapestry-prismic updated
None
Regression testing for all brands.
---
> WEB-10367: package tapestry-prismic updated

- package.json
points to the new version of tapestry 
none
see https://github.com/holidayextras/the-works/pull/564
nope
---
> FP-285: Fix redis connection drop

- lib/pluginTapestry.js
- package.json
- test/pluginTapestryTest.js
https://hxshortbreaks.atlassian.net/browse/FP-2311
Adds brand to prismic query
None
Best tested with the other PRs in the set...
See the-works PR - https://github.com/holidayextras/the-works/pull/667
None
---
> Fp 2311 - Add brands to prismic query

- .github/PULL_REQUEST_TEMPLATE.md
- lib/pluginTapestry.js
- package.json
- test/expected/ABC123Arguments.json
- test/fixtures/ABC123Key.json
- test/fixtures/noCode.json
https://hxshortbreaks.atlassian.net/browse/FP-3625
Passes brand down to Tapestry calls
Amended tests to reflect additional argument
Alongside https://github.com/holidayextras/the-works/pull/672
None
---
> fix the tests

- package.json
[FP-3996](https://hxshortbreaks.atlassian.net/browse/FP-3996): Just pkg updated: tapestry-prismic
---
> FP-3996: Tapestry-prismic pkg version updated

- package.json
[NB-622](https://hxshortbreaks.atlassian.net/browse/NB-622): Updated tapestry-prismic pkg
None
Look at the jira ticket
---
> NB-622: Updated tapestry-prismic pkg

- package.json
Related to https://github.com/holidayextras/tapestry/pull/14 and https://github.com/holidayextras/the-works/pull/1048.
---
> Fp12870 log exodus results

- lib/pluginTapestry.js
- package-lock.json
- package.json
Stops passing The Works logger into Tapestry, we don't use the logs so i'm removing stuff we push to Loggly.
No additional tests.
Fire up https://github.com/holidayextras/the-works/pull/1153 locally and run something like http://localhost:3000/hotelEventProducts/THTOLY_CBRBIE
No …
> dont pass our logger in to tapestry

- package.json
See https://github.com/holidayextras/tapestry-exodus/pull/9 for explanation.
---
> Bump the version of tapestry-exodus

- package-lock.json
- package.json
Partially reverts this change https://github.com/holidayextras/plugin-tapestry/pull/47
---
> Revert to previous version of the tapestry-exodus dependency

- package-lock.json
- package.json
See https://github.com/holidayextras/tapestry-exodus/pull/10
---
> Version bump for tapestry-exodus
